// <auto-generated />
using System;
using Lexicon_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lexicon_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220831133810_Added Countries")]
    partial class AddedCountries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lexicon_MVC.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Gothenburg",
                            CountryId = 1
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Oslo",
                            CountryId = 2
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Helsinki",
                            CountryId = 3
                        });
                });

            modelBuilder.Entity("Lexicon_MVC.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "Finland"
                        });
                });

            modelBuilder.Entity("Lexicon_MVC.Models.Person", b =>
                {
                    b.Property<int?>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PersonId"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("CityId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            CityId = 1,
                            Name = "Marko Kivi",
                            PhoneNumber = "031 123 345"
                        },
                        new
                        {
                            PersonId = 2,
                            CityId = 2,
                            Name = "Emil Kivi",
                            PhoneNumber = "031 222 333"
                        },
                        new
                        {
                            PersonId = 3,
                            CityId = 1,
                            Name = "Johnny Brott",
                            PhoneNumber = "08 666 777"
                        },
                        new
                        {
                            PersonId = 4,
                            CityId = 3,
                            Name = "Håkan Bråkan",
                            PhoneNumber = "040 111 555"
                        });
                });

            modelBuilder.Entity("Lexicon_MVC.Models.City", b =>
                {
                    b.HasOne("Lexicon_MVC.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Lexicon_MVC.Models.Person", b =>
                {
                    b.HasOne("Lexicon_MVC.Models.City", "City")
                        .WithMany("People")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Lexicon_MVC.Models.City", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("Lexicon_MVC.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
