// <auto-generated />
using System;
using Lexicon_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lexicon_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lexicon_MVC.Models.Person", b =>
                {
                    b.Property<int?>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PersonId"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            City = "Gothenburg",
                            Name = "Marko Kivi",
                            PhoneNumber = "031 123 345"
                        },
                        new
                        {
                            PersonId = 2,
                            City = "Gothenburg",
                            Name = "Emil Kivi",
                            PhoneNumber = "031 222 333"
                        },
                        new
                        {
                            PersonId = 3,
                            City = "Stockholm",
                            Name = "Johnny Brott",
                            PhoneNumber = "08 666 777"
                        },
                        new
                        {
                            PersonId = 4,
                            City = "Helsingborg",
                            Name = "Håkan Bråkan",
                            PhoneNumber = "040 111 555"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
